-- create VIDEOSTART_DLT to store the data after data transfermation
CREATE OR REPLACE TABLE "DE04"."VIDEO"."VIDEOSTART_DLT" (
"DATETIME" datetime NOT NULL, 
"PLATFORM" VARCHAR(200) NOT NULL, 
"SITE" VARCHAR(200) NOT NULL, 
"VIDEO" VARCHAR(200) NOT NULL
);