CREATE OR REPLACE TABLE "DE04"."VIDEO"."FACTVIDEOSTART" 
(	
"DATETIME_SKEY" int NOT NULL, 
"PLATFORM_SKEY" int NOT NULL, 
"SITE_SKEY" int NOT NULL, 
"VIDEO_SKEY" int NOT NULL,
"INSERT_DT"	datetime	NOT NULL
);
