INSERT INTO FACTVIDEOSTART
SELECT DD.DATETIME_SKEY, DP.PLATFORM_SKEY, DS.SITE_SKEY, DV.VIDEO_SKEY, CURRENT_TIMESTAMP FROM VIDEOSTART_DLT VSD
LEFT JOIN DIMDATE DD ON TO_CHAR(VSD.DATETIME,'YYYYMMDDHH24MI') = DD.DATETIME
LEFT JOIN DIMPLATFORM DP ON VSD.PLATFORM = DP.PLATFORM
LEFT JOIN DIMSITE DS ON VSD.SITE = DS.SITE
LEFT JOIN DIMVIDEO DV ON VSD.VIDEO = DV.VIDEO;